language: smalltalk
sudo: false

os: linux

jobs: 
  include:

    - stage: "Stable smalltalk versions"
    - smalltalk: GemStone-3.3.6

smalltalk_config: .smalltalkA.ston

cache:
  directories:
    - $SMALLTALK_CI_CACHE
